camunda:
  image: camunda/camunda-bpm-platform:tomcat-7.4.0-alpha1
  environment:
    - DB_DRIVER=org.postgresql.Driver
    - DB_URL=jdbc:postgresql://db:5432/camunda
    - DB_USERNAME=camunda
    - DB_PASSWORD=camunda
  volumes:
    - $PWD/target/docker-demo-invoice.war:/camunda/webapps/docker-demo-invoice.war
  links:
    - db
  ports:
    - "8080"

db:
  image: postgres
  environment:
    - POSTGRES_USER=camunda
    - POSTGRES_PASSWORD=camunda
